### PR TITLE
created basic bubble_sort method that returns a sorted array in ascen…

### PR DESCRIPTION
**Pull request by mosesmuchemi**
Creating a pull request for TSE, Stickler, Peer-to-Peer review.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required 
### Hi @mosesmuchemi  and @dannkkie :wave: 
Great work on the buble sort methods :clap: 
However, I cannot approve this project since [stickler.ci](https://stickler-ci.com/) has not been activated on the repository.
Let's activate it and submit another request for review.

**Happy Coding :computer: 
Simon Wathigo**

**Comment by mosesmuchemi** [comment]
I had problems with Stickler CI so I used linter in local environment.
linter

**Review by whiz25 — APPROVED** [review]
## Well done :+1: 
I understand stickler has failed to detect your repo that happens at times. **I am approving your PR but make sure you make your README more professional before merging as described here**:
 - [ ] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Martin Afani

**Comment by mosesmuchemi** [comment]
Thank you TSE team for the descriptive advice. We will be difinitely applying it going forward

**Pull request merged**
